HPE May 2023

diff --git a/bin/fuse-overlayfs-wrap b/bin/fuse-overlayfs-wrap
--- a/bin/fuse-overlayfs-wrap
+++ b/bin/fuse-overlayfs-wrap
@@ -21,7 +21,10 @@ if [ "$1" = "wait" ] ; then
     echo "Calling umount -v $3" >> $LOG
     for i in $(seq $UMOUNT_WAIT_RETRIES); do
         umount -v $3 >> $LOG 2>&1
-"fuse-overlayfs-wrap" 50L, 1458B                                                                                  1,1           Top
+        if [ $? -ne 0 ]; then
+            # Sleep to let podman clean up
+            echo "Retry umount after sleep $UMOUNT_WAIT_DELAY second(s)" >> $LOG
+            sleep $UMOUNT_WAIT_DELAY
         else
             break
         fi
